/* tslint:disable */
/* eslint-disable */
/**
 * azuki-api
 * github.com/sylms/azuki api document
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    Req,
    ReqFromJSON,
    ReqToJSON,
} from '../models';

export interface GetCsvRequest {
    req?: Req;
}

/**
 * 
 */
export class CsvApi extends runtime.BaseAPI {

    /**
     * CSV をダウンロード 
     * /csv
     */
    async getCsvRaw(requestParameters: GetCsvRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/csv`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ReqToJSON(requestParameters.req),
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     * CSV をダウンロード 
     * /csv
     */
    async getCsv(requestParameters: GetCsvRequest = {}, initOverrides?: RequestInit): Promise<string> {
        const response = await this.getCsvRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
