/* tslint:disable */
/* eslint-disable */
/**
 * azuki-api
 * github.com/sylms/azuki api document
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    FacetTermFacet,
    FacetTermFacetFromJSON,
    FacetTermFacetFromJSONTyped,
    FacetTermFacetToJSON,
} from './FacetTermFacet';

/**
 * ファセット検索のレスポンス
 * @export
 * @interface Facet
 */
export interface Facet {
    /**
     * 
     * @type {FacetTermFacet}
     * @memberof Facet
     */
    termFacet?: FacetTermFacet;
}

export function FacetFromJSON(json: any): Facet {
    return FacetFromJSONTyped(json, false);
}

export function FacetFromJSONTyped(json: any, ignoreDiscriminator: boolean): Facet {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'termFacet': !exists(json, 'term_facet') ? undefined : FacetTermFacetFromJSON(json['term_facet']),
    };
}

export function FacetToJSON(value?: Facet | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'term_facet': FacetTermFacetToJSON(value.termFacet),
    };
}

